PACKAGE_NAME="ipu-bridge-gc2607"
PACKAGE_VERSION="1.0"

BUILT_MODULE_NAME[0]="ipu-bridge"
BUILT_MODULE_LOCATION[0]="./"
DEST_MODULE_LOCATION[0]="/extra"

MAKE="make -C /lib/modules/${kernelver}/build M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build modules"

PRE_BUILD="dkms-prebuild.sh"
POST_INSTALL="dkms-postinstall.sh"

AUTOINSTALL="yes"
